### ISSUE TITLE
How to create an Image that can be put onto a spiflash using an ch341a programmer

### ISSUE THREAD

**Issue by thatsitipl** [OpenNuvoton/N32905_NonOS_Tool#1]
I wanted to ask if it's possible to create an Bootable image that can be written onto an spiflash using an ch341a programmer.
Without needing to connect the N32905 to the pc.

Any help would be appreciated.

**Comment by thatsitipl** [comment]
And i also wanted to mention that this Chip is inside a radio. And i only have acces to the spiflash.

**Comment by kchuang1** [comment]
Do you want to de-solder the SPI flash then use ch341a to program the code into SPI flash and solder it again?

If your device has the SD card slot, you can use the SpiWriter example to update code to SPI flash.

Another way is to use another N32905 device and prepare the SPI booting image.
Read the raw data from SPI flash by turbowriter then use ch341a to program the dump SPI raw data into SPI flash.

**Comment by thatsitipl** [comment]
1.I am not planing on de-soldering the chip because i was able to dump the original firmware with it.
2.The Device unfortunately doesn't have an sd card slot.
3.I don't wan't do buy a new device but if it's the only way i might do that.

Can you create an binary with turbowriter without having to connect a board?
if not
Would it be possible to create an image manually or is it too difficult?
Is it possible to get the turbowriter source?

**Comment by thatsitipl** [comment]
I also want to know how i can connect the N32905U3DN to my pc.
So that i can use it with turbowriter.
I haven't seen any page in the documentation.

And if i buy a new board which shuld i use?

**Comment by kchuang1** [comment]
Due to the loader may be customized by manufacturer, it may still not work after I provided the binary code.

You can change the power-on-setting pin ND[0] to 0 to reboot as Recovery mode. 
So, you need to check the the schematic of your device from manufacturer where is the ND[0].
Refer the "TurboWRiter Tool User Guide.pdf" to connect TurboWriter with Recovery mode for your device.
[Power_On_Setting.pdf](https://github.com/OpenNuvoton/N32905_NonOS_Tool/files/8057138/Power_On_Setting.pdf)

Although, the way can guide you to connect your device to TurboWriter.
The other code still may make your device malfunction.
The best way is to contact the manufacturer for help.

**Comment by thatsitipl** [comment]
Could you give me the binary because than I can check if this is even worth it. I would provide the binary of the board if you want.

**Comment by thatsitipl** [comment]
The size has to be 4mb.

**Comment by thatsitipl** [comment]
And if I can get the device into recovery which USB port should I use

**Comment by thatsitipl** [comment]
If here aren't any updates i will give up and close this issue in a few days.

**Comment by kchuang1** [comment]
if you still want to try the SPIloader, you can try to build the SPILoader at below link.
https://github.com/OpenNuvoton/N32905_NonOS_BSP/tree/master/Loader/SpiLoader/SpiLoader 

Please note that it may still not work because this loader is for general not for your device.
